minVersion: '0.9.0'
github:
    owner: getsentry
    repo: sentry-php
changelogPolicy: simple
statusProvider: 
    name: github
preReleaseCommand: ""
targets:
    - name: github
      includeNames: /none/
    - name: registry
      type: sdk
      config:
          canonical: 'composer:sentry/sentry'
