minVersion: '0.7.0'
github:
    owner: getsentry
    repo: sentry-php
changelogPolicy: simple
targets:
    - name: github
    - name: registry
      type: sdk
      config:
          canonical: 'composer:sentry/sentry'
