minVersion: 0.9.0
github:
  owner: getsentry
  repo: sentry-php
changelogPolicy: simple
statusProvider:
  name: github
artifactProvider:
  name: none
preReleaseCommand: ""
targets:
  - name: github
  - name: registry
    type: sdk
    config:
      canonical: 'composer:sentry/sentry'
