tools:
  external_code_coverage:
    timeout: 2400 # There can be another pull request in progress
    runs: 1

build:
  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run

filter:
  paths: 
    - src/
    - tests/
