tools:
    php_sim: false
    php_pdepend: true
    php_analyzer: true

build:
    environment:
        php:
            version: 5.6.0
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --verbose --configuration phpunit.xml --coverage-clover test/clover.xml'
                coverage:
                    file: 'test/clover.xml'
                    format: 'clover'
    environment:
        redis: false
        postgresql: false
        mongodb: false

filter:
    excluded_paths: [vendor/*, test/*, bin/*, docs/*, examples/*, test/*]
