tools:
    php_cs_fixer: false
    external_code_coverage:
        runs: 1

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

filter:
    paths:
        - src/
        - tests/
