tools:
    php_sim: false
    php_pdepend: true
    php_analyzer: true
    php_code_coverage: true
    external_code_coverage:
        timeout: 2400 # There can be another pull request in progress
        runs: 7 # PHP 5.3 + PHP 5.4 + PHP 5.5 + PHP 5.6 + PHP 7.0 + PHP 7.1 + PHP 7.2  

build:
    environment:
        php:
            version: 5.6.0
        redis: false
        postgresql: false
        mongodb: false

filter:
    excluded_paths: [vendor/*, test/*, bin/*, docs/*, examples/*]
