comment: false
ignore:
  - tests/data
  - tests/resources
  - tests/Fixtures

coverage:
  status:
    project:
      default:
        threshold: 0.1%  # allow for 0.1% reduction of coverage without failing
