[source]
paths = ["src"]
includes = ["vendor"]
excludes = [
    "tests/resources/**",
    "tests/Fixtures/**",
    "src/Util/ClockMock.php",
    "vendor/open-telemetry/gen-otlp-protobuf/GPBMetadata/**",
]

[analyzer]
baseline = "analysis-baseline.toml"
ignore = [
    { code = "no-value", pattern = "DebugType::getDebugType" },
    "impossible-condition",
    "redundant-logical-operation",
]
