name: 🐞 Bug Report
description: Tell us about something that's not working the way we (probably) intend.
body:
  - type: dropdown
    id: type
    attributes:
      label: How do you use Sentry?
      options:
        - Sentry SaaS (sentry.io)
        - Self-hosted / on-premises
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SDK Version
      description: Which SDK version do you use?
      placeholder: e.g. 3.20.1
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. What
        2. you
        3. did.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots? Yes, please.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
    validations:
      required: false
