name: Changelog Preview
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - edited
    - labeled
    - unlabeled
permissions:
  contents: write
  pull-requests: write

jobs:
  changelog-preview:
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@3dc647fee3586e57c7c31eb900fdec7cbb44f23f # v2
    secrets: inherit
